#!/bin/bash

DIR=/var/jb/usr/bin

if [ -f ${DIR}/afc2dSupport ]; then
    chmod 6755 ${DIR}/afc2dSupport
    chown 0:0 ${DIR}/afc2dSupport
else
    chmod 6755 /usr/bin/afc2dSupport
    chown 0:0 /usr/bin/afc2dSupport
fi

exit 0
