#!/bin/bash

if [[ $1 == install || update ]]; then
    echo "" > /usr/libexec/afc2dSupport
    chmod 777 /usr/libexec/afc2dSupport
    
    chown root:wheel /usr/bin/killdaemon
    chmod 6755 /usr/bin/killdaemon
fi

exit 0
